
/* 
    Copyright (c) 1997-2016 Miller Puckette and others.
*/

/* < https://opensource.org/licenses/BSD-3-Clause > */

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

#include "m_pd.h"
#include "m_core.h"

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

t_symbol s_pointer  = { "pointer"   , NULL, NULL };         /* Shared. */
t_symbol s_float    = { "float"     , NULL, NULL };         /* Shared. */
t_symbol s_symbol   = { "symbol"    , NULL, NULL };         /* Shared. */
t_symbol s_bang     = { "bang"      , NULL, NULL };         /* Shared. */
t_symbol s_list     = { "list"      , NULL, NULL };         /* Shared. */
t_symbol s_anything = { "anything"  , NULL, NULL };         /* Shared. */
t_symbol s_signal   = { "signal"    , NULL, NULL };         /* Shared. */
t_symbol s__N       = { "#N"        , NULL, NULL };         /* Shared. */
t_symbol s__X       = { "#X"        , NULL, NULL };         /* Shared. */
t_symbol s__A       = { "#A"        , NULL, NULL };         /* Shared. */
t_symbol s_         = { ""          , NULL, NULL };         /* Shared. */

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

/* Shared. */

t_symbol *sym___TEMPLATE__float__dash__array;
t_symbol *sym___TEMPLATE__text;
t_symbol *sym___ampersand__;
t_symbol *sym___ampersand____ampersand__;
t_symbol *sym___asterisk__;
t_symbol *sym___asterisk____tilde__;
t_symbol *sym___bar__;
t_symbol *sym___bar____bar__;
t_symbol *sym___comma__;
t_symbol *sym___dash__;
t_symbol *sym___dash__c;
t_symbol *sym___dash__curve;
t_symbol *sym___dash__i;
t_symbol *sym___dash__inhibit;
t_symbol *sym___dash__s;
t_symbol *sym___dash__symbol;
t_symbol *sym___dash__v;
t_symbol *sym___dash__visible;
t_symbol *sym___dash__w;
t_symbol *sym___dash__width;
t_symbol *sym___dash__x;
t_symbol *sym___dash__y;
t_symbol *sym___dot__;
t_symbol *sym___equals____equals__;
t_symbol *sym___exclamation____equals__;
t_symbol *sym___greater__;
t_symbol *sym___greater____equals__;
t_symbol *sym___greater____greater__;
t_symbol *sym___hash__A;
t_symbol *sym___hash__N;
t_symbol *sym___hash__X;
t_symbol *sym___less__;
t_symbol *sym___less____equals__;
t_symbol *sym___less____less__;
t_symbol *sym___minus__;
t_symbol *sym___minus____tilde__;
t_symbol *sym___parenthesis__pointer__parenthesis__;
t_symbol *sym___percent__;
t_symbol *sym___plus__;
t_symbol *sym___plus____tilde__;
t_symbol *sym___semicolon__;
t_symbol *sym___slash__;
t_symbol *sym___slash____tilde__;
t_symbol *sym__array;
t_symbol *sym__arraydialog;
t_symbol *sym__audiodialog;
t_symbol *sym__audioproperties;
t_symbol *sym__bendin;
t_symbol *sym__canvasdialog;
t_symbol *sym__copy;
t_symbol *sym__ctlin;
t_symbol *sym__cut;
t_symbol *sym__data;
t_symbol *sym__duplicate;
t_symbol *sym__dummy;
t_symbol *sym__end;
t_symbol *sym__floatarraytemplate;
t_symbol *sym__floattemplate;
t_symbol *sym__font;
t_symbol *sym__gatomdialog;
t_symbol *sym__iemdialog;
t_symbol *sym__key;
t_symbol *sym__keyup;
t_symbol *sym__keyname;
t_symbol *sym__map;
t_symbol *sym__midiclkin;
t_symbol *sym__mididialog;
t_symbol *sym__midiin;
t_symbol *sym__midiproperties;
t_symbol *sym__midirealtimein;
t_symbol *sym__notein;
t_symbol *sym__paste;
t_symbol *sym__path;
t_symbol *sym__pgmin;
t_symbol *sym__polytouchin;
t_symbol *sym__pop;
t_symbol *sym__popupdialog;
t_symbol *sym__quit;
t_symbol *sym__savepreferences;
t_symbol *sym__selectall;
t_symbol *sym__signoff;
t_symbol *sym__sysexin;
t_symbol *sym__texttemplate;
t_symbol *sym__touchin;
t_symbol *sym__watchdog;
t_symbol *sym_abs;
t_symbol *sym_abs__tilde__;
t_symbol *sym_adc__tilde__;
t_symbol *sym_add;
t_symbol *sym_addcomma;
t_symbol *sym_adddollar;
t_symbol *sym_adddollarsymbol;
t_symbol *sym_addline;
t_symbol *sym_addsemicolon;
t_symbol *sym_addword;
t_symbol *sym_append;
t_symbol *sym_array;
t_symbol *sym_array__space__define;
t_symbol *sym_array__space__get;
t_symbol *sym_array__space__max;
t_symbol *sym_array__space__min;
t_symbol *sym_array__space__quantile;
t_symbol *sym_array__space__random;
t_symbol *sym_array__space__set;
t_symbol *sym_array__space__size;
t_symbol *sym_array__space__sum;
t_symbol *sym_atan;
t_symbol *sym_atan2;
t_symbol *sym_atom;
t_symbol *sym_b;
t_symbol *sym_backgroundcolor;
t_symbol *sym_bag;
t_symbol *sym_bang;
t_symbol *sym_bang__tilde__;
t_symbol *sym_bang2;
t_symbol *sym_bendin;
t_symbol *sym_bendout;
t_symbol *sym_bindlist;
t_symbol *sym_biquad__tilde__;
t_symbol *sym_block__tilde__;
t_symbol *sym_bng;
t_symbol *sym_bounds;
t_symbol *sym_bp__tilde__;
t_symbol *sym_buttonsnumber;
t_symbol *sym_callback;
t_symbol *sym_canvas;
t_symbol *sym_canvasmaker;
t_symbol *sym_catch__tilde__;
t_symbol *sym_change;
t_symbol *sym_clear;
t_symbol *sym_click;
t_symbol *sym_clip;
t_symbol *sym_clip__tilde__;
t_symbol *sym_close;
t_symbol *sym_cnv;
t_symbol *sym_color;
t_symbol *sym_comment;
t_symbol *sym_connect;
t_symbol *sym_constant;
t_symbol *sym_coords;
t_symbol *sym_cos;
t_symbol *sym_cos__tilde__;
t_symbol *sym_cosinesum;
t_symbol *sym_cpole__tilde__;
t_symbol *sym_cputime;
t_symbol *sym_ctlin;
t_symbol *sym_ctlout;
t_symbol *sym_czero__tilde__;
t_symbol *sym_czero_rev__tilde__;
t_symbol *sym_dac__tilde__;
t_symbol *sym_data;
t_symbol *sym_dbtopow;
t_symbol *sym_dbtopow__tilde__;
t_symbol *sym_dbtorms;
t_symbol *sym_dbtorms__tilde__;
t_symbol *sym_del;
t_symbol *sym_delay;
t_symbol *sym_delread__tilde__;
t_symbol *sym_delwrite__tilde__;
t_symbol *sym_deselect;
t_symbol *sym_dirty;
t_symbol *sym_disconnect;
t_symbol *sym_displace;
t_symbol *sym_div;
t_symbol *sym_drawcurve;
t_symbol *sym_drawnumber;
t_symbol *sym_drawpolygon;
t_symbol *sym_drawtext;
t_symbol *sym_drawsymbol;
t_symbol *sym_dsp;
t_symbol *sym_editmode;
t_symbol *sym_element;
t_symbol *sym_empty;
t_symbol *sym_env__tilde__;
t_symbol *sym_exp;
t_symbol *sym_exp__tilde__;
t_symbol *sym_f;
t_symbol *sym_fft__tilde__;
t_symbol *sym_file__dot____percent__d;
t_symbol *sym_filledcurve;
t_symbol *sym_filledpolygon;
t_symbol *sym_ft1;
t_symbol *sym_ft2;
t_symbol *sym_flashtime;
t_symbol *sym_float;
t_symbol *sym_floatatom;
t_symbol *sym_flush;
t_symbol *sym_foregroundcolor;
t_symbol *sym_format;
t_symbol *sym_framp__tilde__;
t_symbol *sym_fromsymbol;
t_symbol *sym_fswap;
t_symbol *sym_ftom;
t_symbol *sym_ftom__tilde__;
t_symbol *sym_gatom;
t_symbol *sym_get;
t_symbol *sym_getposition;
t_symbol *sym_getsize;
t_symbol *sym_guiconnect;
t_symbol *sym_guistub;
t_symbol *sym_graph;
t_symbol *sym_gripsize;
t_symbol *sym_hip__tilde__;
t_symbol *sym_hold;
t_symbol *sym_hradio;
t_symbol *sym_hslider;
t_symbol *sym_i;
t_symbol *sym_ifft__tilde__;
t_symbol *sym_initialize;
t_symbol *sym_inlet;
t_symbol *sym_inlet__tilde__;
t_symbol *sym_int;
t_symbol *sym_key;
t_symbol *sym_keyname;
t_symbol *sym_keyup;
t_symbol *sym_label;
t_symbol *sym_labelcolor;
t_symbol *sym_labelfont;
t_symbol *sym_labelposition;
t_symbol *sym_length;
t_symbol *sym_line;
t_symbol *sym_line__tilde__;
t_symbol *sym_linear;
t_symbol *sym_linewidth;
t_symbol *sym_list;
t_symbol *sym_list__space__append;
t_symbol *sym_list__space__fromsymbol;
t_symbol *sym_list__space__inlet;
t_symbol *sym_list__space__length;
t_symbol *sym_list__space__prepend;
t_symbol *sym_list__space__split;
t_symbol *sym_list__space__tosymbol;
t_symbol *sym_list__space__trim;
t_symbol *sym_listen;
t_symbol *sym_loadbang;
t_symbol *sym_log;
t_symbol *sym_log__tilde__;
t_symbol *sym_logarithmic;
t_symbol *sym_lop__tilde__;
t_symbol *sym_makefilename;
t_symbol *sym_makenote;
t_symbol *sym_max;
t_symbol *sym_max__tilde__;
t_symbol *sym_merge;
t_symbol *sym_message;
t_symbol *sym_messageresponder;
t_symbol *sym_metro;
t_symbol *sym_midiclkin;
t_symbol *sym_midiin;
t_symbol *sym_midiout;
t_symbol *sym_midirealtimein;
t_symbol *sym_min;
t_symbol *sym_min__tilde__;
t_symbol *sym_mod;
t_symbol *sym_moses;
t_symbol *sym_motion;                                        
t_symbol *sym_mouse;
t_symbol *sym_mouseup;
t_symbol *sym_move;
t_symbol *sym_msg;
t_symbol *sym_mtof;
t_symbol *sym_mtof__tilde__;
t_symbol *sym_namecanvas;
t_symbol *sym_nbx;
t_symbol *sym_netreceive;
t_symbol *sym_netsend;
t_symbol *sym_new;
t_symbol *sym_next;
t_symbol *sym_nextselected;
t_symbol *sym_noise__tilde__;
t_symbol *sym_nonzero;
t_symbol *sym_normalize;
t_symbol *sym_notein;
t_symbol *sym_noteout;
t_symbol *sym_number;
t_symbol *sym_obj;
t_symbol *sym_objectmaker;
t_symbol *sym_open;
t_symbol *sym_openpanel;
t_symbol *sym_osc__tilde__;
t_symbol *sym_oscformat;
t_symbol *sym_oscparse;
t_symbol *sym_outlet;
t_symbol *sym_outlet__tilde__;
t_symbol *sym_pack;
t_symbol *sym_pad;
t_symbol *sym_panelsize;
t_symbol *sym_pd;
t_symbol *sym_phasor__tilde__;
t_symbol *sym_pipe;
t_symbol *sym_pgmin;
t_symbol *sym_pgmout;
t_symbol *sym_plot;
t_symbol *sym_pointer;
t_symbol *sym_poly;
t_symbol *sym_polytouchin;
t_symbol *sym_polytouchout;
t_symbol *sym_position;
t_symbol *sym_pow;
t_symbol *sym_pow__tilde__;
t_symbol *sym_powtodb;
t_symbol *sym_powtodb__tilde__;
t_symbol *sym_prepend;
t_symbol *sym_print;
t_symbol *sym_print__tilde__;
t_symbol *sym_qlist;
t_symbol *sym_quit;
t_symbol *sym_r;
t_symbol *sym_r__tilde__;
t_symbol *sym_radio;
t_symbol *sym_random;
t_symbol *sym_range;
t_symbol *sym_read;
t_symbol *sym_readsf__tilde__;
t_symbol *sym_realtime;
t_symbol *sym_receive;
t_symbol *sym_receive__tilde__;
t_symbol *sym_rename;
t_symbol *sym_reset;
t_symbol *sym_resize;
t_symbol *sym_restore;
t_symbol *sym_rewind;
t_symbol *sym_rfft__tilde__;
t_symbol *sym_rifft__tilde__;
t_symbol *sym_rmstodb;
t_symbol *sym_rmstodb__tilde__;
t_symbol *sym_route;
t_symbol *sym_rpole__tilde__;
t_symbol *sym_rsqrt__tilde__;
t_symbol *sym_rzero__tilde__;
t_symbol *sym_rzero_rev__tilde__;
t_symbol *sym_s;
t_symbol *sym_s__tilde__;
t_symbol *sym_samphold__tilde__;
t_symbol *sym_samplerate__tilde__;
t_symbol *sym_save;
t_symbol *sym_saveas;
t_symbol *sym_savepanel;
t_symbol *sym_savetofile;
t_symbol *sym_scalar;
t_symbol *sym_scalar__space__define;
t_symbol *sym_scale;
t_symbol *sym_seed;
t_symbol *sym_sel;
t_symbol *sym_select;
t_symbol *sym_send;
t_symbol *sym_sendwindow;
t_symbol *sym_send__tilde__;
t_symbol *sym_serial;
t_symbol *sym_set;
t_symbol *sym_setsize;
t_symbol *sym_sig__tilde__;
t_symbol *sym_signal;
t_symbol *sym_sin;
t_symbol *sym_sinesum;
t_symbol *sym_size;
t_symbol *sym_slider;
t_symbol *sym_snapshot__tilde__;
t_symbol *sym_soundfiler;
t_symbol *sym_spigot;
t_symbol *sym_split;
t_symbol *sym_sqrt;
t_symbol *sym_sqrt__tilde__;
t_symbol *sym_start;
t_symbol *sym_steady;
t_symbol *sym_step;
t_symbol *sym_steps;
t_symbol *sym_stop;
t_symbol *sym_struct;
t_symbol *sym_stripnote;
t_symbol *sym_style;
t_symbol *sym_subpatch;
t_symbol *sym_swap;
t_symbol *sym_switch__tilde__;
t_symbol *sym_symbol;
t_symbol *sym_symbolatom;
t_symbol *sym_sysexin;
t_symbol *sym_t;
t_symbol *sym_table;
t_symbol *sym_tabosc4__tilde__;
t_symbol *sym_tabplay__tilde__;
t_symbol *sym_tabread;
t_symbol *sym_tabread__tilde__;
t_symbol *sym_tabread4;
t_symbol *sym_tabread4__tilde__;
t_symbol *sym_tabsend__tilde__;
t_symbol *sym_tabreceive__tilde__;
t_symbol *sym_tabwrite;
t_symbol *sym_tabwrite__tilde__;
t_symbol *sym_tan;
t_symbol *sym_template;
t_symbol *sym_text;
t_symbol *sym_text__space__define;
t_symbol *sym_text__space__fromlist;
t_symbol *sym_text__space__get;
t_symbol *sym_text__space__search;
t_symbol *sym_text__space__sequence;
t_symbol *sym_text__space__set;
t_symbol *sym_text__space__size;
t_symbol *sym_text__space__tolist;
t_symbol *sym_textfile;
t_symbol *sym_tgl;
t_symbol *sym_threshold__tilde__;
t_symbol *sym_throw__tilde__;
t_symbol *sym_timer;
t_symbol *sym_tosymbol;
t_symbol *sym_touchin;
t_symbol *sym_touchout;
t_symbol *sym_traverse;
t_symbol *sym_trigger;
t_symbol *sym_trim;
t_symbol *sym_unit;
t_symbol *sym_unpack;
t_symbol *sym_until;
t_symbol *sym_v;
t_symbol *sym_value;
t_symbol *sym_vcf__tilde__;
t_symbol *sym_vd__tilde__;
t_symbol *sym_visible;
t_symbol *sym_vline__tilde__;
t_symbol *sym_vradio;
t_symbol *sym_vslider;
t_symbol *sym_vsnapshot__tilde__;
t_symbol *sym_vu;
t_symbol *sym_w;
t_symbol *sym_window;
t_symbol *sym_wrap;
t_symbol *sym_wrap__tilde__;
t_symbol *sym_write;
t_symbol *sym_writesf__tilde__;
t_symbol *sym_x;
t_symbol *sym_y;
t_symbol *sym_z;
t_symbol *sym_BackSpace;
t_symbol *sym_Delete;
t_symbol *sym_Down;
t_symbol *sym_Enter;
t_symbol *sym_Escape;
t_symbol *sym_Left;
t_symbol *sym_Space;
t_symbol *sym_Return;
t_symbol *sym_Right;
t_symbol *sym_Tab;
t_symbol *sym_Up;

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

#if PD_WITH_LEGACY

t_symbol *sym_add2;
t_symbol *sym_adddollsym;
t_symbol *sym_addsemi;
t_symbol *sym_args;
t_symbol *sym_auto;
t_symbol *sym_const;
t_symbol *sym_delta;
t_symbol *sym_double_change;
t_symbol *sym_get_pos;
t_symbol *sym_hsl;
t_symbol *sym_init;
t_symbol *sym_label_font;
t_symbol *sym_label_pos;
t_symbol *sym_lin;
t_symbol *sym_log_height;
t_symbol *sym_menu__dash__open;
t_symbol *sym_menuarray;
t_symbol *sym_menuclose;
t_symbol *sym_menusave;
t_symbol *sym_menusaveas;
t_symbol *sym_mergefile;
t_symbol *sym_my_canvas;
t_symbol *sym_my_numbox;
t_symbol *sym_mycnv;
t_symbol *sym_numbox;
t_symbol *sym_page;
t_symbol *sym_pos;
t_symbol *sym_q8_rsqrt__tilde__;
t_symbol *sym_q8_sqrt__tilde__;
t_symbol *sym_send__dash__window;
t_symbol *sym_setbounds;
t_symbol *sym_single_change;
t_symbol *sym_tempo;
t_symbol *sym_toggle;
t_symbol *sym_vis;
t_symbol *sym_vis_size;
t_symbol *sym_vnext;
t_symbol *sym_vsl;
t_symbol *sym_vumeter;

#endif

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

void symbols_initialize (void)
{ 
    sym___TEMPLATE__float__dash__array          = utils_makeBindSymbol (gensym ("float-array"));
    sym___TEMPLATE__text                        = utils_makeBindSymbol (gensym ("text"));
    sym___ampersand__                           = gensym ("&");
    sym___ampersand____ampersand__              = gensym ("&&");
    sym___asterisk__                            = gensym ("*");
    sym___asterisk____tilde__                   = gensym ("*~");
    sym___bar__                                 = gensym ("|");
    sym___bar____bar__                          = gensym ("||");
    sym___comma__                               = gensym (",");
    sym___dash__                                = gensym ("-");
    sym___dash__c                               = gensym ("-c");
    sym___dash__curve                           = gensym ("-curve");
    sym___dash__i                               = gensym ("-i");
    sym___dash__inhibit                         = gensym ("-inhibit");
    sym___dash__s                               = gensym ("-s");
    sym___dash__symbol                          = gensym ("-symbol");
    sym___dash__v                               = gensym ("-v");
    sym___dash__visible                         = gensym ("-visible");
    sym___dash__w                               = gensym ("-w");
    sym___dash__width                           = gensym ("-width");
    sym___dash__x                               = gensym ("-x");
    sym___dash__y                               = gensym ("-y");
    sym___dot__                                 = gensym (".");
    sym___equals____equals__                    = gensym ("==");
    sym___exclamation____equals__               = gensym ("!=");
    sym___greater__                             = gensym (">");
    sym___greater____equals__                   = gensym (">=");
    sym___greater____greater__                  = gensym (">>");
    sym___hash__A                               = gensym ("#A");
    sym___hash__N                               = gensym ("#N");
    sym___hash__X                               = gensym ("#X");
    sym___less__                                = gensym ("<");
    sym___less____equals__                      = gensym ("<=");
    sym___less____less__                        = gensym ("<<");
    sym___minus__                               = gensym ("-");
    sym___minus____tilde__                      = gensym ("-~");
    sym___parenthesis__pointer__parenthesis__   = gensym ("(pointer)");
    sym___percent__                             = gensym ("%");
    sym___plus__                                = gensym ("+");
    sym___plus____tilde__                       = gensym ("+~");
    sym___semicolon__                           = gensym (";");
    sym___slash__                               = gensym ("/");
    sym___slash____tilde__                      = gensym ("/~");
    sym__array                                  = gensym ("_array");
    sym__arraydialog                            = gensym ("_arraydialog");
    sym__audiodialog                            = gensym ("_audiodialog");
    sym__audioproperties                        = gensym ("_audioproperties");
    sym__bendin                                 = gensym ("_bendin");
    sym__canvasdialog                           = gensym ("_canvasdialog");
    sym__copy                                   = gensym ("_copy");
    sym__ctlin                                  = gensym ("_ctlin");
    sym__cut                                    = gensym ("_cut");
    sym__data                                   = gensym ("_data");
    sym__duplicate                              = gensym ("_duplicate");
    sym__end                                    = gensym ("_end");
    sym__dummy                                  = gensym ("_dummy");
    sym__floatarraytemplate                     = gensym ("_floatarraytemplate");
    sym__floattemplate                          = gensym ("_floattemplate");
    sym__font                                   = gensym ("_font");
    sym__gatomdialog                            = gensym ("_gatomdialog");
    sym__iemdialog                              = gensym ("_iemdialog");
    sym__key                                    = gensym ("_key");
    sym__keyup                                  = gensym ("_keyup");
    sym__keyname                                = gensym ("_keyname");
    sym__map                                    = gensym ("_map");
    sym__midiclkin                              = gensym ("_midiclkin");
    sym__mididialog                             = gensym ("_mididialog");
    sym__midiin                                 = gensym ("_midiin");
    sym__midiproperties                         = gensym ("_midiproperties");
    sym__midirealtimein                         = gensym ("_midirealtimein");
    sym__notein                                 = gensym ("_notein");
    sym__paste                                  = gensym ("_paste");
    sym__path                                   = gensym ("_path");
    sym__pgmin                                  = gensym ("_pgmin");
    sym__polytouchin                            = gensym ("_polytouchin");
    sym__pop                                    = gensym ("_pop");
    sym__popupdialog                            = gensym ("_popupdialog");
    sym__quit                                   = gensym ("_quit");
    sym__savepreferences                        = gensym ("_savepreferences");
    sym__selectall                              = gensym ("_selectall");
    sym__signoff                                = gensym ("_signoff");
    sym__sysexin                                = gensym ("_sysexin");
    sym__texttemplate                           = gensym ("_texttemplate");
    sym__touchin                                = gensym ("_touchin");
    sym__watchdog                               = gensym ("_watchdog");
    sym_abs                                     = gensym ("abs");
    sym_abs__tilde__                            = gensym ("abs~");
    sym_adc__tilde__                            = gensym ("adc~"),
    sym_add                                     = gensym ("add");
    sym_addcomma                                = gensym ("addcomma");
    sym_adddollar                               = gensym ("adddollar");
    sym_adddollarsymbol                         = gensym ("adddollarsymbol");
    sym_addline                                 = gensym ("addline");
    sym_addsemicolon                            = gensym ("addsemicolon");
    sym_addword                                 = gensym ("addword");
    sym_append                                  = gensym ("append");
    sym_array                                   = gensym ("array");
    sym_array__space__define                    = gensym ("array define");
    sym_array__space__get                       = gensym ("array get");
    sym_array__space__max                       = gensym ("array max");
    sym_array__space__min                       = gensym ("array min");
    sym_array__space__quantile                  = gensym ("array quantile");
    sym_array__space__random                    = gensym ("array random");
    sym_array__space__set                       = gensym ("array set");
    sym_array__space__size                      = gensym ("array size");
    sym_array__space__sum                       = gensym ("array sum");
    sym_atan                                    = gensym ("atan");
    sym_atan2                                   = gensym ("atan2");
    sym_atom                                    = gensym ("atom");
    sym_b                                       = gensym ("b");
    sym_backgroundcolor                         = gensym ("backgroundcolor");
    sym_bag                                     = gensym ("bag");
    sym_bang                                    = gensym ("bang");
    sym_bang__tilde__                           = gensym ("bang~");
    sym_bang2                                   = gensym ("bang2");
    sym_bendin                                  = gensym ("bendin");
    sym_bendout                                 = gensym ("bendout");
    sym_bindlist                                = gensym ("bindlist");
    sym_biquad__tilde__                         = gensym ("biquad~");
    sym_block__tilde__                          = gensym ("block~");
    sym_bng                                     = gensym ("bng");
    sym_bounds                                  = gensym ("bounds");
    sym_bp__tilde__                             = gensym ("bp~");
    sym_buttonsnumber                           = gensym ("buttonsnumber");
    sym_callback                                = gensym ("callback");
    sym_canvas                                  = gensym ("canvas");
    sym_canvasmaker                             = gensym ("canvasmaker");
    sym_catch__tilde__                          = gensym ("catch~");
    sym_change                                  = gensym ("change");
    sym_clear                                   = gensym ("clear");
    sym_click                                   = gensym ("click");
    sym_clip                                    = gensym ("clip");
    sym_clip__tilde__                           = gensym ("clip~");
    sym_close                                   = gensym ("close");
    sym_cnv                                     = gensym ("cnv");
    sym_color                                   = gensym ("color");
    sym_comment                                 = gensym ("comment");
    sym_connect                                 = gensym ("connect");
    sym_constant                                = gensym ("constant");
    sym_coords                                  = gensym ("coords");
    sym_cos                                     = gensym ("cos");
    sym_cos__tilde__                            = gensym ("cos~");
    sym_cosinesum                               = gensym ("cosinesum");
    sym_cpole__tilde__                          = gensym ("cpole~");
    sym_cputime                                 = gensym ("cputime");
    sym_ctlin                                   = gensym ("ctlin");
    sym_ctlout                                  = gensym ("ctlout");
    sym_czero__tilde__                          = gensym ("czero~");
    sym_czero_rev__tilde__                      = gensym ("czero_rev~");
    sym_dac__tilde__                            = gensym ("dac~");
    sym_data                                    = gensym ("data");
    sym_dbtopow                                 = gensym ("dbtopow");
    sym_dbtopow__tilde__                        = gensym ("dbtopow~");
    sym_dbtorms                                 = gensym ("dbtorms");
    sym_dbtorms__tilde__                        = gensym ("dbtorms~");
    sym_del                                     = gensym ("del");
    sym_delay                                   = gensym ("delay");
    sym_delread__tilde__                        = gensym ("delread~");
    sym_delwrite__tilde__                       = gensym ("delwrite~");
    sym_deselect                                = gensym ("deselect");
    sym_dirty                                   = gensym ("dirty");
    sym_disconnect                              = gensym ("disconnect");
    sym_displace                                = gensym ("displace");
    sym_div                                     = gensym ("div");
    sym_drawcurve                               = gensym ("drawcurve");
    sym_drawnumber                              = gensym ("drawnumber");
    sym_drawpolygon                             = gensym ("drawpolygon");
    sym_drawtext                                = gensym ("drawtext");
    sym_drawsymbol                              = gensym ("drawsymbol");
    sym_dsp                                     = gensym ("dsp");
    sym_editmode                                = gensym ("editmode");
    sym_element                                 = gensym ("element");
    sym_empty                                   = gensym ("empty");
    sym_env__tilde__                            = gensym ("env~");
    sym_exp                                     = gensym ("exp");
    sym_exp__tilde__                            = gensym ("exp~");
    sym_f                                       = gensym ("f");
    sym_fft__tilde__                            = gensym ("fft~");
    sym_file__dot____percent__d                 = gensym ("file.%d");
    sym_filledcurve                             = gensym ("filledcurve");
    sym_filledpolygon                           = gensym ("filledpolygon");
    sym_ft1                                     = gensym ("ft1");
    sym_ft2                                     = gensym ("ft2");
    sym_flashtime                               = gensym ("flashtime");
    sym_float                                   = gensym ("float");
    sym_floatatom                               = gensym ("floatatom");
    sym_flush                                   = gensym ("flush");
    sym_foregroundcolor                         = gensym ("foregroundcolor");
    sym_format                                  = gensym ("format");
    sym_framp__tilde__                          = gensym ("framp~");
    sym_fromsymbol                              = gensym ("fromsymbol");
    sym_fswap                                   = gensym ("fswap");
    sym_ftom                                    = gensym ("ftom");
    sym_ftom__tilde__                           = gensym ("ftom~");
    sym_gatom                                   = gensym ("gatom");
    sym_get                                     = gensym ("get");
    sym_getposition                             = gensym ("getposition");
    sym_getsize                                 = gensym ("getsize");
    sym_guiconnect                              = gensym ("guiconnect");
    sym_guistub                                 = gensym ("guistub");
    sym_graph                                   = gensym ("graph");
    sym_gripsize                                = gensym ("gripsize");
    sym_hip__tilde__                            = gensym ("hip~");
    sym_hold                                    = gensym ("hold");
    sym_hradio                                  = gensym ("hradio");
    sym_hslider                                 = gensym ("hslider");
    sym_i                                       = gensym ("i");
    sym_ifft__tilde__                           = gensym ("ifft~");
    sym_initialize                              = gensym ("initialize");
    sym_inlet                                   = gensym ("inlet");
    sym_inlet__tilde__                          = gensym ("inlet~");
    sym_int                                     = gensym ("int");
    sym_key                                     = gensym ("key");
    sym_keyname                                 = gensym ("keyname");
    sym_keyup                                   = gensym ("keyup");
    sym_label                                   = gensym ("label");
    sym_labelcolor                              = gensym ("labelcolor");
    sym_labelfont                               = gensym ("labelfont");
    sym_labelposition                           = gensym ("labelposition");
    sym_length                                  = gensym ("length");
    sym_line                                    = gensym ("line");
    sym_line__tilde__                           = gensym ("line~");
    sym_linear                                  = gensym ("linear");
    sym_linewidth                               = gensym ("linewidth");
    sym_list                                    = gensym ("list");
    sym_list__space__append                     = gensym ("list append");
    sym_list__space__fromsymbol                 = gensym ("list fromsymbol");
    sym_list__space__inlet                      = gensym ("list inlet");
    sym_list__space__length                     = gensym ("list length");
    sym_list__space__prepend                    = gensym ("list prepend");
    sym_list__space__split                      = gensym ("list split");
    sym_list__space__tosymbol                   = gensym ("list tosymbol");
    sym_list__space__trim                       = gensym ("list trim");
    sym_listen                                  = gensym ("listen");
    sym_loadbang                                = gensym ("loadbang");
    sym_log                                     = gensym ("log");
    sym_log__tilde__                            = gensym ("log~");
    sym_logarithmic                             = gensym ("logarithmic");
    sym_lop__tilde__                            = gensym ("lop~");
    sym_makefilename                            = gensym ("makefilename");
    sym_makenote                                = gensym ("makenote");
    sym_max                                     = gensym ("max");
    sym_max__tilde__                            = gensym ("max~");
    sym_merge                                   = gensym ("merge");
    sym_message                                 = gensym ("message");
    sym_messageresponder                        = gensym ("messageresponder");
    sym_metro                                   = gensym ("metro");
    sym_midiclkin                               = gensym ("midiclkin");
    sym_midiin                                  = gensym ("midiin");
    sym_midiout                                 = gensym ("midiout");
    sym_midirealtimein                          = gensym ("midirealtimein");
    sym_min                                     = gensym ("min");
    sym_min__tilde__                            = gensym ("min~");
    sym_mod                                     = gensym ("mod");
    sym_moses                                   = gensym ("moses");
    sym_motion                                  = gensym ("motion");
    sym_mouse                                   = gensym ("mouse");
    sym_mouseup                                 = gensym ("mouseup");
    sym_move                                    = gensym ("move");
    sym_msg                                     = gensym ("msg");
    sym_mtof                                    = gensym ("mtof");
    sym_mtof__tilde__                           = gensym ("mtof~");
    sym_namecanvas                              = gensym ("namecanvas");
    sym_nbx                                     = gensym ("nbx");
    sym_netreceive                              = gensym ("netreceive");
    sym_netsend                                 = gensym ("netsend");
    sym_new                                     = gensym ("new");
    sym_next                                    = gensym ("next");
    sym_nextselected                            = gensym ("nextselected");
    sym_noise__tilde__                          = gensym ("noise~");
    sym_nonzero                                 = gensym ("nonzero");
    sym_normalize                               = gensym ("normalize");
    sym_notein                                  = gensym ("notein");
    sym_noteout                                 = gensym ("noteout");
    sym_number                                  = gensym ("number");
    sym_obj                                     = gensym ("obj");
    sym_objectmaker                             = gensym ("objectmaker");
    sym_open                                    = gensym ("open");
    sym_openpanel                               = gensym ("openpanel");
    sym_osc__tilde__                            = gensym ("osc~");
    sym_oscformat                               = gensym ("oscformat");
    sym_oscparse                                = gensym ("oscparse");
    sym_outlet                                  = gensym ("outlet");
    sym_outlet__tilde__                         = gensym ("outlet~");
    sym_pack                                    = gensym ("pack");
    sym_pad                                     = gensym ("pad");
    sym_panelsize                               = gensym ("panelsize");
    sym_pd                                      = gensym ("pd");
    sym_phasor__tilde__                         = gensym ("phasor~");
    sym_pipe                                    = gensym ("pipe");
    sym_pgmin                                   = gensym ("pgmin");
    sym_pgmout                                  = gensym ("pgmout");
    sym_plot                                    = gensym ("plot");
    sym_pointer                                 = gensym ("pointer");
    sym_poly                                    = gensym ("poly");
    sym_polytouchin                             = gensym ("polytouchin");
    sym_polytouchout                            = gensym ("polytouchout");
    sym_position                                = gensym ("position");
    sym_pow                                     = gensym ("pow");
    sym_pow__tilde__                            = gensym ("pow~");
    sym_powtodb                                 = gensym ("powtodb");
    sym_powtodb__tilde__                        = gensym ("powtodb~");
    sym_prepend                                 = gensym ("prepend");
    sym_print                                   = gensym ("print");
    sym_print__tilde__                          = gensym ("print~");
    sym_qlist                                   = gensym ("qlist");
    sym_quit                                    = gensym ("quit");
    sym_r                                       = gensym ("r");
    sym_r__tilde__                              = gensym ("r~");
    sym_radio                                   = gensym ("radio");
    sym_random                                  = gensym ("random");
    sym_range                                   = gensym ("range");
    sym_read                                    = gensym ("read");
    sym_readsf__tilde__                         = gensym ("readsf~");
    sym_realtime                                = gensym ("realtime");
    sym_receive                                 = gensym ("receive");
    sym_receive__tilde__                        = gensym ("receive~");
    sym_rename                                  = gensym ("rename");
    sym_reset                                   = gensym ("reset");
    sym_resize                                  = gensym ("resize");
    sym_restore                                 = gensym ("restore");
    sym_rewind                                  = gensym ("rewind");
    sym_rfft__tilde__                           = gensym ("rfft~");
    sym_rifft__tilde__                          = gensym ("rifft~");
    sym_rmstodb                                 = gensym ("rmstodb");
    sym_rmstodb__tilde__                        = gensym ("rmstodb~");
    sym_route                                   = gensym ("route");
    sym_rpole__tilde__                          = gensym ("rpole~");
    sym_rzero__tilde__                          = gensym ("rzero~");
    sym_rsqrt__tilde__                          = gensym ("rsqrt~");
    sym_rzero_rev__tilde__                      = gensym ("rzero_rev~");
    sym_s                                       = gensym ("s");
    sym_s__tilde__                              = gensym ("s~");
    sym_samphold__tilde__                       = gensym ("samphold~");
    sym_samplerate__tilde__                     = gensym ("samplerate~");
    sym_save                                    = gensym ("save");
    sym_saveas                                  = gensym ("saveas");
    sym_savepanel                               = gensym ("savepanel");
    sym_savetofile                              = gensym ("savetofile");
    sym_scalar                                  = gensym ("scalar");
    sym_scalar__space__define                   = gensym ("scalar define");
    sym_scale                                   = gensym ("scale");
    sym_seed                                    = gensym ("seed");
    sym_sel                                     = gensym ("sel");
    sym_select                                  = gensym ("select");
    sym_send                                    = gensym ("send");
    sym_sendwindow                              = gensym ("sendwindow");
    sym_send__tilde__                           = gensym ("send~");
    sym_serial                                  = gensym ("serial");
    sym_set                                     = gensym ("set");
    sym_setsize                                 = gensym ("setsize");
    sym_sig__tilde__                            = gensym ("sig~");
    sym_signal                                  = gensym ("signal");
    sym_sin                                     = gensym ("sin");
    sym_sinesum                                 = gensym ("sinesum");
    sym_size                                    = gensym ("size");
    sym_slider                                  = gensym ("slider");
    sym_snapshot__tilde__                       = gensym ("snapshot~");
    sym_soundfiler                              = gensym ("soundfiler");
    sym_spigot                                  = gensym ("spigot");
    sym_split                                   = gensym ("split");
    sym_sqrt                                    = gensym ("sqrt");
    sym_sqrt__tilde__                           = gensym ("sqrt~");
    sym_start                                   = gensym ("start");
    sym_steady                                  = gensym ("steady");
    sym_step                                    = gensym ("step");
    sym_steps                                   = gensym ("steps");
    sym_stop                                    = gensym ("stop");
    sym_stripnote                               = gensym ("stripnote");
    sym_struct                                  = gensym ("struct");
    sym_style                                   = gensym ("style");
    sym_subpatch                                = gensym ("subpatch");
    sym_swap                                    = gensym ("swap");
    sym_switch__tilde__                         = gensym ("switch~");
    sym_symbol                                  = gensym ("symbol");
    sym_symbolatom                              = gensym ("symbolatom");
    sym_sysexin                                 = gensym ("sysexin");
    sym_t                                       = gensym ("t");
    sym_table                                   = gensym ("table");
    sym_tabosc4__tilde__                        = gensym ("tabosc4~");
    sym_tabplay__tilde__                        = gensym ("tabplay~");
    sym_tabread                                 = gensym ("tabread");
    sym_tabread__tilde__                        = gensym ("tabread~");
    sym_tabread4                                = gensym ("tabread4");
    sym_tabread4__tilde__                       = gensym ("tabread4~");
    sym_tabreceive__tilde__                     = gensym ("tabreceive~");
    sym_tabsend__tilde__                        = gensym ("tabsend~");
    sym_tabwrite                                = gensym ("tabwrite");
    sym_tabwrite__tilde__                       = gensym ("tabwrite~");
    sym_tan                                     = gensym ("tan");
    sym_template                                = gensym ("template");
    sym_text                                    = gensym ("text");
    sym_text__space__define                     = gensym ("text define");
    sym_text__space__fromlist                   = gensym ("text fromlist");
    sym_text__space__get                        = gensym ("text get");
    sym_text__space__search                     = gensym ("text search");
    sym_text__space__sequence                   = gensym ("text sequence");
    sym_text__space__set                        = gensym ("text set");
    sym_text__space__size                       = gensym ("text size");
    sym_text__space__tolist                     = gensym ("text tolist");
    sym_textfile                                = gensym ("textfile");
    sym_tgl                                     = gensym ("tgl");
    sym_threshold__tilde__                      = gensym ("threshold~");
    sym_throw__tilde__                          = gensym ("throw~");
    sym_timer                                   = gensym ("timer");
    sym_tosymbol                                = gensym ("tosymbol");
    sym_touchin                                 = gensym ("touchin");
    sym_touchout                                = gensym ("touchout");
    sym_traverse                                = gensym ("traverse");
    sym_trigger                                 = gensym ("trigger");
    sym_trim                                    = gensym ("trim");
    sym_unit                                    = gensym ("unit");
    sym_unpack                                  = gensym ("unpack");
    sym_until                                   = gensym ("until");
    sym_v                                       = gensym ("v");
    sym_value                                   = gensym ("value");
    sym_vcf__tilde__                            = gensym ("vcf~");
    sym_vd__tilde__                             = gensym ("vd~");
    sym_visible                                 = gensym ("visible");
    sym_vline__tilde__                          = gensym ("vline~");
    sym_vradio                                  = gensym ("vradio");
    sym_vslider                                 = gensym ("vslider");
    sym_vsnapshot__tilde__                      = gensym ("vsnapshot~");
    sym_vu                                      = gensym ("vu");
    sym_w                                       = gensym ("w");
    sym_window                                  = gensym ("window");
    sym_wrap                                    = gensym ("wrap");
    sym_wrap__tilde__                           = gensym ("wrap~");
    sym_write                                   = gensym ("write");
    sym_writesf__tilde__                        = gensym ("writesf~");
    sym_x                                       = gensym ("x");
    sym_y                                       = gensym ("y");
    sym_z                                       = gensym ("z");
    sym_BackSpace                               = gensym ("BackSpace");
    sym_Delete                                  = gensym ("Delete");
    sym_Down                                    = gensym ("Down");
    sym_Enter                                   = gensym ("Enter");
    sym_Escape                                  = gensym ("Escape");
    sym_Left                                    = gensym ("Left");
    sym_Return                                  = gensym ("Return");
    sym_Right                                   = gensym ("Right");
    sym_Space                                   = gensym ("Space");
    sym_Tab                                     = gensym ("Tab");
    sym_Up                                      = gensym ("Up");
    
    #if PD_WITH_LEGACY

    sym_add2                                    = gensym ("add2");
    sym_adddollsym                              = gensym ("adddollsym");
    sym_addsemi                                 = gensym ("addsemi");
    sym_args                                    = gensym ("args");
    sym_auto                                    = gensym ("auto");
    sym_const                                   = gensym ("const");
    sym_delta                                   = gensym ("delta");
    sym_double_change                           = gensym ("double_change");
    sym_get_pos                                 = gensym ("get_pos");
    sym_hsl                                     = gensym ("hsl");
    sym_init                                    = gensym ("init");
    sym_label_font                              = gensym ("label_font");
    sym_label_pos                               = gensym ("label_pos");
    sym_lin                                     = gensym ("lin");
    sym_log_height                              = gensym ("log_height");
    sym_menu__dash__open                        = gensym ("menu-open");
    sym_menuarray                               = gensym ("menuarray");
    sym_menuclose                               = gensym ("menuclose");
    sym_menusave                                = gensym ("menusave");
    sym_menusaveas                              = gensym ("menusaveas");
    sym_mergefile                               = gensym ("mergefile");
    sym_my_canvas                               = gensym ("my_canvas");
    sym_my_numbox                               = gensym ("my_numbox");
    sym_mycnv                                   = gensym ("mycnv");
    sym_numbox                                  = gensym ("numbox");
    sym_page                                    = gensym ("page");
    sym_pos                                     = gensym ("pos");
    sym_q8_rsqrt__tilde__                       = gensym ("q8_rsqrt~");
    sym_q8_sqrt__tilde__                        = gensym ("q8_sqrt~");
    sym_send__dash__window                      = gensym ("send-window");
    sym_setbounds                               = gensym ("setbounds");
    sym_single_change                           = gensym ("single_change");
    sym_tempo                                   = gensym ("tempo");
    sym_toggle                                  = gensym ("toggle");
    sym_vis                                     = gensym ("vis");
    sym_vis_size                                = gensym ("vis_size");
    sym_vnext                                   = gensym ("vnext");
    sym_vsl                                     = gensym ("vsl");
    sym_vumeter                                 = gensym ("vumeter");
    
    #endif
}

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
